### PR TITLE
added all msg types server to client

### PR DESCRIPTION
**Pull request by Kogs**

### CODE REVIEW

**Comment by ThunderGemios10** [comment]
Thanks!

**Comment by ThunderGemios10** [comment]
Also, The Template for Protocol.md is at https://github.com/OgarioProject/Agar.io-Protocol

**Comment by Kogs** [comment]
Im currently in finding out what which msg does. And if am done with it. I'll maybe write it nicely down here.  This is not that easy because the game.js is minified and hard to read.

**Comment by ThunderGemios10** [comment]
@Kogs, Yes I know, It is quite hard to deobfuscate the code.

**Pull request merged**
