### PR TITLE
slither debug utility

### PR DESCRIPTION
**Pull request by sitano**

### CODE REVIEW

**Comment by Mat2095** [comment]
In case you have closed the PR because I've merged the other two but not this one:
I would totally be okay with this being added, but since it's different from the other stuff I don'd see myself in a position where I can decide that, so I would have let a "senior member" decide :)

**Comment by sitano** [comment]
Thx for the comment) I thought this do not fit very well into the repo along the protocol definition, yet being a great tool though.

**Comment by sitano** [comment]
Any resolution on that one?

**Comment by Mat2095** [comment]
I'll just merge it. If someone has a problem with this, I'm sorry, just revert it then.

**Comment by sitano** [comment]
you can check it if you want, install it with tampermonkey

**Pull request merged**
