### PR TITLE
Added Message a

### PR DESCRIPTION
**Pull request by Kogs**
All Variables in the Message 'a' descripted (as good I could right now)

### CODE REVIEW

**Comment by ThunderGemios10** [comment]
A 2nd pull request right off the bat? How about i give you push access instead?
Also Thanks!

**Comment by ThunderGemios10** [comment]
@Kogs Also, Are messages packets?

**Comment by Kogs** [comment]
Messages are packets yes.

**Comment by ThunderGemios10** [comment]
@Kogs, Ok, Please refer to them as packets then.. Messages are confusing.. Also i gave you push access to this repo.

**Pull request merged**
