### PR TITLE
Fix formatting in protocol file

### PR DESCRIPTION
**Pull request by zrneely**
I hope this doesn't sound rude, that's not my intent! I think my changes help make the protocol documentation easier to read. I also didn't intentionally change the meaning of anything.

### CODE REVIEW

**Comment by ThunderGemios10** [comment]
Hmmm, This is really hard to decide if i should merge or not, Then again i'm not very familiar with JavaScript, I'll let @Kogs take this one.

**Comment by zrneely** [comment]
I don't think this change involves any Javascript, it just helps make the Markdown file describing the protocol more readable. There's no new information added or old information removed.

**Comment by ThunderGemios10** [comment]
@zrneely I know, It's just that this pull request has alot of formatting changes, So i don't know if i should merge as of the moment. Again, I'll let @Kogs take care of this.

**Comment by Kogs** [comment]
@zrneely 
1. Thanks for your Help improving the document.
2. The "Message Types" Table is broken. If you fix it. We can merge the pull request.

**Comment by zrneely** [comment]
I've fixed the merge conflicts, which (I think) fixed the Message Types table.

**Comment by ThunderGemios10** [comment]
Ok thanks!

**Comment by ThunderGemios10** [comment]
@zrneely Your message types table is still broken..

**Comment by Kogs** [comment]
I fixed it. @zrneely thanks for the help anyway.if you See grammer or other erros feel free to create another Pull request

**Pull request merged**
